### ISSUE TITLE
php $

### ISSUE THREAD

**Issue by ildarkhasanshin** [CudaText-addons/cuda_complete_from_text#10]
`Plugin supports CudaText option "nonword_chars", so for example words with '$' can be added, if option is configured so.`

копался в
```specials = '$%#-'```
```-+*=/\()[]{}<>"'.,:;~?!@#$%^&|`…```
и в `nonword_chars` из `lexer PHP.json`
но так и не смог настроить, чтоб плагин вставлял с $

**Comment by Alexey-T** [comment]
что искал в какой позиции какого текста?
что предложил плагин?

**Comment by ildarkhasanshin** [comment]
```<?php
$data = 'test';

da|
```

в списке выводится
```
text data
..
```

нажимаем enter
получаем `data`
вместо `$data`

**Comment by Alexey-T** [comment]
нашел проблему в плаге. вот тут `def get_regex` надо удалить `\b` :
```
    return r'[%s]{%d,}' % (cls, option_min_len)
```

затем в опциях плагина дать
```
[complete_from_text]
lexers=-,ini files,markdown,restructuredtext,properties,mediawiki,php,php_
```
затем в файлах `lexer PHP.json`, `lexer PHP_.json` дать
```
{
  "nonword_chars": "-+*=/\\()[]{}<>\"'.,:;~?!@#%^&|`…",

}
```
тогда для доллара дает слова $data и $test

@veksha давайте поищем недочеты у фикса плага.

**Comment by ildarkhasanshin** [comment]
так робит
```
|$
```

так нет
```
$|
```

**Comment by veksha** [comment]
у меня работает (тестировал для `lexer: none`). убрал `\b` из regex и `$` из nonword_chars в Options Editor Lite.

**Comment by Alexey-T** [comment]
у меня работает и так и так. вот конфиг плага
```

[complete_from_text]
lexers=-,ini files,markdown,restructuredtext,properties,mediawiki,php,php_
min_len=3
case_sens=0
no_comments=0
no_strings=0
what_editors=0
max_lines=10000
use_acp=0
case_split=0
underscore_split=0
```

**Comment by veksha** [comment]
на пустой строке не работает и не работает вот так: |$
у меня работает только так: $|

**Comment by ildarkhasanshin** [comment]
`what_editors=1`
`|$` - список из текущей вкладки
`$|` - список из всех вкладок

**Comment by ildarkhasanshin** [comment]
другой вопрос

```
$data = 'data';
$test = 'test';

da|
```

возможно в таком случае в списке получать
```
var $data
text data
..
```
?

сейчас только так можно подставить переменную

```
$data = 'data';
$test = 'test';

$da|
```

**Comment by Alexey-T** [comment]
думаю что можно- если вернуть доллар в nonword_chars.
