### ISSUE TITLE
css hyphen

### ISSUE THREAD

**Issue by ildarkhasanshin** [CudaText-addons/cuda_complete_from_text#13]
```
p {
  border-radius: 5px;
}

span {
  bo|
}
```
выводится `border`, вместо `border-radius`
т.е. обрезается до `-`

**Comment by Alexey-T** [comment]
complete from text? он не должен работать для цсс. для цсс юзай встроенное autocomplete. а не этот плаг


![Screenshot_2023-01-31_21-14-56](https://user-images.githubusercontent.com/4154978/215847705-6db5512c-8165-413f-846b-625cbc8e3f20.png)

**Comment by Alexey-T** [comment]
убери цсс из этой опции плага


[complete_from_text]
lexers=-,ini files,markdown,restructuredtext,properties,html,php

**Comment by ildarkhasanshin** [comment]
>он не должен работать для цсс

но у нас не только свойства могут быть с дефисом
но и сами названия

```
p.header-line {
  |
}
```

**Comment by Alexey-T** [comment]
попробуй удалить знак минус, из опции nonword_chars.

**Comment by ildarkhasanshin** [comment]
пробовал - не помогло

**Comment by Alexey-T** [comment]
https://github.com/CudaText-addons/cuda_complete_from_text/issues/13#issuecomment-1411456391

что ты тут хочешь получить по autocomplete? как на ето влияет название "p.header-line"? запутался я.

**Comment by ildarkhasanshin** [comment]
в идеале `p.header-line`, `.header-line` и `header-line`
чтоб можно было оперировать ими в дальнейшей работе

**Comment by Alexey-T** [comment]
css autocomplete не умеет понимать имена классов юзера.
и это надо править css completion а не каккой-то левый плагин complete from text.

есть еще HTML Completion plugin. не для цсс.

**Comment by Alexey-T** [comment]
есть еще эти два плага.
![Screenshot_2023-02-01_15-50-28](https://user-images.githubusercontent.com/4154978/216047914-f2e972da-dc56-4b7c-b764-35af2334bfec.png)

**Comment by Alexey-T** [comment]
еще раз. про первый твой пост. запретил css autocomplete, и убрал минус из опции nonword_chars для цсс лексера.

стало все ок. выводит подсказки с минусом.

![Screenshot_2023-02-01_16-21-02](https://user-images.githubusercontent.com/4154978/216054750-ac2945b0-940f-4768-a2d3-1acb271e5350.png)

**Comment by ildarkhasanshin** [comment]
> убрал минус из опции nonword_chars для цсс лексера

а-а-а, в lexer CSS.json - теперь и у меня ок
