### ISSUE TITLE
acp files- comments

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_complete_from_text#2]
special comments in .acp files, e.g. in C++.acp PHP_.acp, did you skip them?
@halfbrained

**Comment by halfbrained** [comment]
`#chars -$[]':`  
In the first line? I did... will be fixing that.

Am I missing something, or included acp files were never used?

**Comment by Alexey-T** [comment]
yes, `#chars` in the 1st line.
acp files were used!

**Comment by halfbrained** [comment]
These chars are irrelevant here, so you meant I need to skip them, right? Did that now. (https://github.com/halfbrained/cuda_complete_from_text/commit/c3a69b15340493f1ff0eb60e7ff4e902021c00cc)

> acp files were used!
Sorry, I was very confused again :D

**Comment by Alexey-T** [comment]
that is good, thanks. and new options.
