### ISSUE TITLE
on choosing item 'compile' from from .acp file

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_complete_from_text#4]
![hh](https://user-images.githubusercontent.com/4154978/109135404-16567100-7768-11eb-9056-e63e1eca3fde.png)

I got too long inserted text
`compile(string, filename, kind[, flags[, dont_inherit]])
`

@halfbrained

**Comment by halfbrained** [comment]
Have a fix, but having trouble testing https://github.com/Alexey-T/CudaText/issues/3194

**Comment by Alexey-T** [comment]
Cud was fixed.

**Comment by halfbrained** [comment]
fixed

Why is `autocomplete/PHP_.acp` has an underscore in it? For the moment I just check for both `lexer.acp` and `lexer_.acp`

(VBScript has some bizarre syntax :D )

**Comment by Alexey-T** [comment]
PHP lexer activates HTML sublexer at start, and after `<?` is activates PHP_ sublexer. PHP_ is real php.

**Comment by Alexey-T** [comment]
for LEXER_AT_POS api, you will get "PHP_" string for the real php lexer, ie PHP_.
